
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: [--py3-plus, --py38-plus]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--safe, --quiet, --line-length=88]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        args: [--disallow-untyped-defs, --disallow-incomplete-defs, --disallow-untyped-calls]
        exclude: 'tests'

  - repo: https://github.com/HunterMcGushion/docstr_coverage
    rev: v2.2.0
    hooks:
      - id: docstr-coverage
        args: ["src", "--verbose", "2"]

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.3
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --docstring-convention=numpy
          - --ban-relative-imports=true
          - --max-function-length=50
        additional_dependencies:
          - flake8-assert-msg==1.1.1
          - flake8-bugbear==22.7.1
          - flake8-builtins==1.4.1
          - flake8-comprehensions==1.4.1
          - flake8-docstrings==1.6.0
          - flake8-functions==0.0.2
          - flake8-tidy-imports==4.6.0
          - pep8-naming==0.12.1
